language: python
python: "3.6"
services: postgresql
before_script:
  - psql -c "CREATE USER chado_user WITH SUPERUSER PASSWORD 'chado_pw';" -U postgres
  - createdb -U postgres -O chado_user chado_user
script: "python setup.py test"
